export const geoData = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.3289, 40.6948],
      },
      properties: {
        name: 'Babylon Main Street Dock',
        address: '200 West Main Street',
        city: 'Babylon',
        state: 'NY',
        zip: 11757,
        shoreline: 'South',
        zone: 'S10A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.3377, 40.675],
      },
      properties: {
        name: 'Bergen Peir',
        address: '600 Bergen Ave',
        city: 'Babylon',
        state: 'NY',
        zip: 11702,
        shoreline: 'South',
        zone: 'S10A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.2576, 40.6422],
      },
      properties: {
        name: 'Captree Boat Launch',
        address: '3500 Ocean pwky east',
        city: 'Babylon',
        state: 'NY',
        zip: 11702,
        shoreline: 'South',
        zone: 'S11B',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.2163, 40.635],
      },
      properties: {
        name: 'Fire Island Lighthouse',
        address: 'Fire Island National Seashore',
        city: 'Babylon',
        state: 'NY',
        zip: 11702,
        shoreline: 'South',
        zone: 'S10A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.2643, 40.6249],
      },
      properties: {
        name: 'Robert Moses Beach Field 3',
        address: '600 Robert Moses State park dr.',
        city: 'Babylon',
        state: 'NY',
        zip: 11702,
        shoreline: 'South',
        zone: 'S10A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.315, 40.6818],
      },
      properties: {
        name: 'Sampawams Point Dock',
        address: '700 Fire Island Ave South',
        city: 'Babylon',
        state: 'NY',
        zip: 11702,
        shoreline: 'South',
        zone: 'S10A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.3512, 40.6687],
      },
      properties: {
        name: 'Venetian Shores Beach',
        address: 'Venetian Shores Park',
        city: 'Babylon',
        state: 'NY',
        zip: 11702,
        shoreline: 'South',
        zone: 'S10A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.2487, 40.7197],
      },
      properties: {
        name: 'Bay Shore Main Street Dock',
        address: '19 Ocean Ave',
        city: 'Bay Shore',
        state: 'NY',
        zip: 11706,
        shoreline: 'South',
        zone: 'S12A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.2366, 40.7119],
      },
      properties: {
        name: 'Bay Shore Manor Park',
        address: 'Bay Shore Manor Park',
        city: 'Bay Shore',
        state: 'NY',
        zip: 11706,
        shoreline: 'South',
        zone: 'S12A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.2393, 40.7136],
      },
      properties: {
        name: 'Bay Shore Peir',
        address: '135 Maple Ave',
        city: 'Bay Shore',
        state: 'NY',
        zip: 11706,
        shoreline: 'South',
        zone: 'S12A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.0523, 40.7315],
      },
      properties: {
        name: 'Bayport ',
        address: 'James Street',
        city: 'Bayport',
        state: 'NY',
        zip: 11705,
        shoreline: 'South',
        zone: 'S16A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.0279, 40.7449],
      },
      properties: {
        name: 'Blue Point Boat Launch',
        address: '3 Curtis Road',
        city: 'Blue Point',
        state: 'NY',
        zip: 11715,
        shoreline: 'South',
        zone: 'S16A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.2588, 40.7112],
      },
      properties: {
        name: 'Brightwaters Dock',
        address: 'Concourse West',
        city: 'Brightwaters',
        state: 'NY',
        zip: 11718,
        shoreline: 'South',
        zone: 'S12A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.8961, 40.7741],
      },
      properties: {
        name: 'Beaver Dam Dock',
        address: '399 Beaver Dam Road',
        city: 'Brookhaven',
        state: 'NY',
        zip: 11719,
        shoreline: 'South',
        zone: 'S20A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.7954, 40.7089],
      },
      properties: {
        name: 'Neville Park',
        address: '48 Crosby Street',
        city: 'Center Morchies',
        state: 'NY',
        zip: 11934,
        shoreline: 'South',
        zone: 'S24A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.7977, 40.785],
      },
      properties: {
        name: 'Union Peir',
        address: '145 Union Ave',
        city: 'Center Morchies',
        state: 'NY',
        zip: 11934,
        shoreline: 'South',
        zone: 'S24A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.3927, 40.6607],
      },
      properties: {
        name: 'Tanner Park Dock',
        address: '129 Kerrigan Road',
        city: 'Copiague',
        state: 'NY',
        zip: 11726,
        shoreline: 'South',
        zone: 'S8A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.1891, 40.7072],
      },
      properties: {
        name: 'Bayview Ave Boat Launch',
        address: '333 Bayview Ave',
        city: 'East Islip',
        state: 'NY',
        zip: 11730,
        shoreline: 'South',
        zone: 'S13A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.1738, 40.7062],
      },
      properties: {
        name: 'Heckscher State Park',
        address: '1 Heckscher Parkway Field',
        city: 'East Islip',
        state: 'NY',
        zip: 11730,
        shoreline: 'South',
        zone: 'S13A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.7536, 40.8011],
      },
      properties: {
        name: 'East Morchies Boat Launch',
        address: '29 Maple Ave',
        city: 'East Morchies',
        state: 'NY',
        zip: 11940,
        shoreline: 'South',
        zone: 'S25A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.9973, 40.7492],
      },
      properties: {
        name: 'East Patchogue Boat Launch',
        address: 'Haven Street',
        city: 'East Patchogue',
        state: 'NY',
        zip: 11772,
        shoreline: 'South',
        zone: 'S18A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.5708, 40.8406],
      },
      properties: {
        name: 'Bay Peir',
        address: '32 Bay Ave',
        city: 'East Quogue',
        state: 'NY',
        zip: 11942,
        shoreline: 'South',
        zone: 'S30A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.7259, 40.8144],
      },
      properties: {
        name: 'Eastport Boat Launch',
        address: '58 South Bay Ave',
        city: 'Eastport',
        state: 'NY',
        zip: 11941,
        shoreline: 'South',
        zone: 'S25A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.5671, 40.6382],
      },
      properties: {
        name: 'Cow Meadow Country Park',
        address: '701 South Main Street',
        city: 'Freeport',
        state: 'NY',
        zip: 11520,
        shoreline: 'South',
        zone: 'S3A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.5817, 40.6345],
      },
      properties: {
        name: 'Nautical Mile',
        address: '195 Woodcleft Ave',
        city: 'Freeport',
        state: 'NY',
        zip: 11520,
        shoreline: 'South',
        zone: 'S3A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.4994, 40.8419],
      },
      properties: {
        name: 'Hampton Bays Boat Launch',
        address: 'Lighthouse Rd',
        city: 'Hampton Bays',
        state: 'NY',
        zip: 11946,
        shoreline: 'South',
        zone: 'S31A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.5307, 40.8288],
      },
      properties: {
        name: 'Tiana Beach',
        address: '89 Dune Road',
        city: 'Hampton Bays',
        state: 'NY',
        zip: 11946,
        shoreline: 'South',
        zone: 'S31A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.2236, 40.7214],
      },
      properties: {
        name: 'Islip Boat Launch',
        address: 'Maple Street',
        city: 'Islip',
        state: 'NY',
        zip: 11751,
        shoreline: 'South',
        zone: 'S13A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.3561, 40.6689],
      },
      properties: {
        name: 'Wellwood Dock',
        address: '854 South Wellwood Ave',
        city: 'Lindenhurst',
        state: 'NY',
        zip: 11757,
        shoreline: 'South',
        zone: 'S9A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.6659, 40.5936],
      },
      properties: {
        name: 'Veterans Memorial Park',
        address: 'Veterans Memorial Park',
        city: 'Long Beach',
        state: 'NY',
        zip: 11561,
        shoreline: 'South',
        zone: 'S1B',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.4474, 40.6622],
      },
      properties: {
        name: 'John J. Burns Park',
        address: '4990 Merrick Road',
        city: 'Massapequa Park',
        state: 'NY',
        zip: 11762,
        shoreline: 'South',
        zone: 'S6A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.8308, 40.7952],
      },
      properties: {
        name: 'Mastic Dock',
        address: '48 Riviera Drive',
        city: 'Mastic',
        state: 'NY',
        zip: 11950,
        shoreline: 'South',
        zone: 'S23A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.8338, 40.7595],
      },
      properties: {
        name: 'The Lagoon',
        address: '101 Riviera Drive',
        city: 'Mastic Beach',
        state: 'NY',
        zip: 11951,
        shoreline: 'South',
        zone: 'S22A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.6628, 40.6257],
      },
      properties: {
        name: 'Bay Park (Boat Launch)',
        address: 'Marjorie Lane',
        city: 'Oceanside',
        state: 'NY',
        zip: 11572,
        shoreline: 'South',
        zone: 'S1A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.0088, 40.747],
      },
      properties: {
        name: 'Patchogue Peir',
        address: 'South Ocean Ave',
        city: 'Patchogue',
        state: 'NY',
        zip: 11772,
        shoreline: 'South',
        zone: 'S17A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.5868, 40.5939],
      },
      properties: {
        name: 'Point Lookout Dock',
        address: '1501 Lido Blvd',
        city: 'Point Lookout',
        state: 'NY',
        zip: 11569,
        shoreline: 'South',
        zone: 'S2B',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.6103, 40.8074],
      },
      properties: {
        name: 'Quogo Neck Peir',
        address: 'Quogo Neck Lane',
        city: 'Quogue',
        state: 'NY',
        zip: 11959,
        shoreline: 'South',
        zone: 'S29A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.0737, 40.7233],
      },
      properties: {
        name: 'Sayville Marina Park',
        address: '30 Browns River Road',
        city: 'Sayville',
        state: 'NY',
        zip: 11782,
        shoreline: 'South',
        zone: 'S15A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.8734, 40.7407],
      },
      properties: {
        name: 'Smiths Point Marina',
        address: 'Duneview Drive',
        city: 'Shirley',
        state: 'NY',
        zip: 11967,
        shoreline: 'South',
        zone: 'S21A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.5142, 40.6477],
      },
      properties: {
        name: 'Wantagh Country Park',
        address: '1 King Street',
        city: 'Wantagh',
        state: 'NY',
        zip: 11793,
        shoreline: 'South',
        zone: 'S5A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.2915, 40.6878],
      },
      properties: {
        name: 'Marina Park',
        address: '100 Beach Drive',
        city: 'West Islip',
        state: 'NY',
        zip: 11702,
        shoreline: 'South',
        zone: 'S11A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-73.0937, 40.7201],
      },
      properties: {
        name: 'West Ave Dock',
        address: 'West Ave',
        city: 'West Sayville',
        state: 'NY',
        zip: 11796,
        shoreline: 'South',
        zone: 'S15A',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-72.6411, 40.8059],
      },
      properties: {
        name: 'Westhampton Boat Launch',
        address: '56 Library Ave',
        city: 'Westhampton Beach',
        state: 'NY',
        zip: 11978,
        shoreline: 'South',
        zone: 'S28A',
      },
    },
  ],
};
